### ISSUE TITLE
Can I borrow some ideas from CBravoR's fork

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/ExplorationPlus#2]
@CBravoR (only way I could figure out how to get hold of you as you don't seem to have a forum presence) - I very much like what you've done with your fork, would you mind if I borrowed some of it? (Full credit will be given of course)

**Comment by CBravoR** [comment]
Hey! I actually tried to message you though the forum when I made the fork. Sadly it does not allow you to when your account is new. Happy for you to use it!

If you let me know what would you like to use I can create a Pull request, might make it easier for you to trace. And note I also used a hack to deactivate the random requirement to return home, but didn't delete the legacy code that generated it. I just changed the Data node to make it irrelevant in the base ExplorationPlus.cfg (generating a random number between  4 and 6 instead of 1 to 3).

This is my favourite contract pack, thanks for creating it!

**Comment by severedsolo** [comment]
I've been toying with the idea of breaking Mopping Up into separate return contracts for a while, so I'm going to steal that wholesale 😛 

Also like what you've done with the vessel labels, so I'll probably steal that too. If you want to ping me your forum username so I can give you  proper credit that would be awesome.

I saw your hack, tbh I'll probably drop that entirely with the new system,

**Comment by CBravoR** [comment]
Excellent, I'll create a pull request for those two then. I'll post at the forum thread them mentioning this, but I would rather keep my screen name separated from my IRL name. 

Oh! I also deleted a few things here and there and added some conditions on the planet generation so Kerbin does not appear, instead of a requirement node which was giving me issues in the CC logs. You'll see all that in the pull request. You can always ask me if anything isn't clear.

I'll keep an eye for the new version then! Thanks for the interest.

**Comment by severedsolo** [comment]
>  I'll post at the forum thread them mentioning this, but I would rather keep my screen name separated from my IRL name.

No worries mate, completely understand that.

**Comment by CBravoR** [comment]
Just posted in the forum, but it's waiting moderator approval. I also created the pull request. Note I didn't know how to selectively pick changes, so the requests cheekily asks to change the github and ownership to me in the ExplorationPlus.cfg, which is of course absurd. Sorry about that.

**Comment by severedsolo** [comment]
Changes merged - thank you very much!
